const types = {
  TOTAL_ASSETS: 'TOTAL_ASSETS',
  VISIBLE_ASSETS: 'VISIBLE_ASSETS',
  ADD_ASSET: 'ADD_ASSET',
  REMOVE_ASSET: 'REMOVE_ASSET',
  ADD_ERROR: 'ADD_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  FILTER_ASSETS: 'FILTER_ASSETS',
};

export default types;
